apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: realestate
  labels:
    app: realestate-api
spec:
  type: ClusterIP
  selector:
    app: realestate-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
