apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: realestate
  labels:
    app: realestate-client
spec:
  type: ClusterIP
  selector:
    app: realestate-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80