apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: realestate
  labels:
    app: realestate-api
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "real_estate"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: realestate
  labels:
    app: realestate-client
data:
  NGINX_WORKER_PROCESSES: "auto"
  API_BACKEND_URL: "http://api:8080"
